apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjblZ6YkdGdU16QXdNVHBuYUhCZlNIRkNaWFJPUkdKek1Vd3pSSEY2TVZkd2NreFlaM0JFZDI1VlZWWjFNakJGVkhOcyJ9fX0=
type: kubernetes.io/dockerconfigjson
